### ISSUE TITLE
Need advice on how to get music working

### ISSUE THREAD

**Issue by LumenCrest** [ivan-hc/Spacecadetpinball-git-appimage#1]
I'm happy I found this AppImage so I can finally try playing the decomp with Full Tilt! rules and soundscape. So far it's working great, but one thing is bothering me: I can't seem to get the music working.

Am I missing something? I tried extraction of the AppImage files to try and play around with this, but I have no clue what if anything is missing, and where to put the missing stuff. It _seems_ like the necessary midis are in fact included, but for some reason they won't work with FluidSynth out of the box compared to the Flatpak.

So how do I get the music to work in this AppImage? I'm stumped.

(Hardware is a Steam Deck LCD 512 GB model.)

**Comment by ivan-hc** [comment]
Thanks to let me know this, I have never used the flatpak and I was not aware about te F6 option to enable the music.

So this game includes other sounds other than the classic Windows XP sounds of the game? I was not aware about this.

**Comment by ivan-hc** [comment]
Anyway nope, it seems that I miss something when I have built it. I'll investigate asap.

**Comment by ivan-hc** [comment]
OK, I have found that thesre is an optional missing package, see the section "Dependencies" at https://aur.archlinux.org/packages/spacecadetpinball-git#dependencies , the package name is "**freepats-general-midi**"

This is the package https://archlinux.org/packages/extra/any/freepats-general-midi/ , I have done the test and the final AppImage increased from 42 MB to 330 MB, i.e about 8-9 times bigger.

I don't think it's worth creating such a big AppImage just for music. What do you think about that?

**Comment by LumenCrest** [comment]
I can certainly start by checking out the links you provided soon, not a problem!

To answer the SFX question, there are a few sound effects in the Full Tilt! version omitted from the 3DPB demo, which surprised me the first time I heard about the "true" full version. One example lies with the mission select targets; there's a more satisfying "pew" added that plays when you hit any of them.

[EDIT] Adding to this, the Full Tilt! version also has a couple of other MIDIs that play during specific events, those being at Mission Start and Multi-ball Activation. I can confirm all the different assets are there as per my dive into the files. [/EDIT]

Thanks for pointing me in the right direction!

**Comment by ivan-hc** [comment]
I close this because I don't plan to add the music.

As I have explained, the package may be 8-9 times bigger than what is needed in the gameplay.

I'll add an advice on the README for this.
